### ISSUE TITLE
FR: Table Header tag

### ISSUE THREAD

**Issue by adrienne** [editor-js/table#45]
Need to be able to add table header rows, please!

**Comment by dgaponov** [comment]
+1

**Comment by hagemann** [comment]
Proposal: add boolean option `withHeader` so that the frontend can render a `<thead>` itself.

**Comment by ranemihir** [comment]
If the `withHeader`property is set, that means if header row is provided by the user then the output data should be returned in the form JSON instead of a matrix. It would be more readable and easy to loop through.

On the other hand, if no header row is provided, output will be returned as a matrix.

**Comment by neSpecc** [comment]
Resolved by #67
